# Generated by Django 3.1.5 on 2021-03-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='contact_number',
            field=models.IntegerField(),
        ),
    ]
