# Generated by Django 3.1.5 on 2021-03-03 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20210303_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contacts.category'),
        ),
    ]
