# Generated by Django 3.1.5 on 2021-03-04 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_auto_20210303_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_number',
            new_name='number',
        ),
    ]
